#!/usr/bin/env python3
import argparse
import asyncio
import aiohttp
import time
from statistics import mean
from collections import defaultdict


BLOCK_KEYWORDS = [
    "header too large",
    "request header",
    "header fields too large",
    "431",
    "too many header",
    "bad request",
    "400",
]


def make_long_value(size_bytes: int, pattern=b'A') -> str:
    # produce ASCII string
    return (pattern * min(size_bytes, 8192)).decode('ascii', errors='ignore') * (size_bytes // 8192 + 1)


async def worker(session, url, case_generator, results):
    """Send requests generated by case_generator and collect metrics."""
    while True:
        start = time.perf_counter()
        try:
            headers, descr = next(case_generator)
            try:
                async with session.get(url, headers=headers) as resp:
                    latency = time.perf_counter() - start
                    results["status_codes"][resp.status] += 1
                    results["latencies"].append(latency)
                    results["success"] += 1

                    text = await resp.text()
                    lowered = text.lower()
                    for kw in BLOCK_KEYWORDS:
                        if kw in lowered:
                            results["block_hits"] += 1
                            results["block_messages"].add(kw)
            except Exception as e:
                # connection reset/socket errors etc
                results["fail"] += 1
                results["exceptions"].append(str(e))

        except asyncio.CancelledError:
            break

        except StopIteration:
            break

        except Exception as e:
            results["fail"] += 1
            results["exceptions"].append(str(e))


def case_generator_factory(max_header_bytes: int, many_headers: int, duplicate_count: int):
    """Yield a sequence of (headers, description) tuples for testing."""
    # Case 1: very long User-Agent
    ua_value = 'A' * max(1, max_header_bytes)
    yield ({'User-Agent': ua_value}, f'long-user-agent-{len(ua_value)}')

    # Case 2: very large Cookie header
    cookie_val = 'k=v;' * (max(1, max_header_bytes // 10))
    yield ({'Cookie': cookie_val}, f'large-cookie-{len(cookie_val)}')

    # Case 3: many small custom headers
    many = {f'X-Test-{i}': 'val' for i in range(many_headers)}
    yield (many, f'many-headers-{many_headers}')

    # Case 4: duplicated header keys (aiohttp client will choose last by default, but some servers get many headers)
    # We simulate duplicates by concatenating values with comma where appropriate
    dup_values = ','.join(['x'] * duplicate_count)
    yield ({'X-Dup': dup_values}, f'duplicated-xdup-{duplicate_count}')

    # Case 5: header name with illegal characters (space) — many clients block this, but try a variant
    try:
        yield ({'Bad Header': 'value'}, 'illegal-header-name-space')
    except Exception:
        # skip if client library rejects
        pass

    # Case 6: incremental size sweep: increasing User-Agent sizes
    for size in [1024, 4096, 16 * 1024, 64 * 1024, 256 * 1024]:
        if size <= max_header_bytes:
            yield ({'User-Agent': 'A' * size}, f'user-agent-sweep-{size}')

    # Case 7: very long header name (some servers limit name length)
    name = 'H' * min(256, max(1, max_header_bytes // 100))
    yield ({name: 'v'}, f'long-header-name-{len(name)}')


async def run_test(url, concurrency, duration, max_header_kb, many_headers, duplicate_count):
    print('\nStarting Header Injection Test')
    print(f'URL: {url}')
    print(f'Concurrency: {concurrency}')
    print(f'Duration: {duration}s')
    print(f'Max header KB (approx): {max_header_kb}')
    print(f'Many headers: {many_headers}')
    print(f'Duplicate count: {duplicate_count}')
    print('------------------------------------\n')

    max_header_bytes = int(max_header_kb * 1024)

    results = {
        'success': 0,
        'fail': 0,
        'latencies': [],
        'status_codes': defaultdict(int),
        'block_hits': 0,
        'block_messages': set(),
        'exceptions': [],
    }

    timeout = aiohttp.ClientTimeout(total=30)
    async with aiohttp.ClientSession(timeout=timeout) as session:
        # Create a cyclic generator
        gen = case_generator_factory(max_header_bytes, many_headers, duplicate_count)
        # make it infinite by cycling
        def cyc():
            while True:
                for item in gen:
                    yield item

        cycle_gen = cyc()

        tasks = [asyncio.create_task(worker(session, url, cycle_gen, results)) for _ in range(concurrency)]

        try:
            await asyncio.sleep(duration)
        finally:
            for t in tasks:
                t.cancel()
            await asyncio.gather(*tasks, return_exceptions=True)

    # Summary
    print('\n====== RAW RESULT DATA ======')
    total = results['success'] + results['fail']
    print(f'Total requests attempted: {total}')
    print(f'Successful: {results["success"]}')
    print(f'Failed: {results["fail"]}')
    print(f'Status codes: {dict(results["status_codes"])}')
    if results['latencies']:
        print(f'Avg latency: {mean(results["latencies"]):.4f}s')
        print(f'Fastest: {min(results["latencies"]):.4f}s')
        print(f'Slowest: {max(results["latencies"]):.4f}s')
    print(f'Block message hits (body): {results["block_hits"]}')
    print(f'Block messages: {results["block_messages"]}')
    if results['exceptions']:
        print('Exceptions (sample):')
        for e in results['exceptions'][:10]:
            print(' -', e)

    # Protection analysis
    print('\n====== PROTECTION ANALYSIS ======')
    protected = False

    if results['status_codes'].get(431, 0) > 0 or results['block_hits'] > 0:
        print('Server enforces header limits (HTTP 431 or block messages).')
        protected = True
    else:
        print('No HTTP 431 or obvious block messages detected.')

    if results['status_codes'].get(400, 0) > 0:
        print('Server returned 400 Bad Request for malformed headers (parsing protections).')
        protected = True

    if results['status_codes'].get(403, 0) > 0:
        print('WAF or firewall blocked requests (HTTP 403).')
        protected = True

    if results['fail'] > 0 and not protected:
        print('Some requests failed (connection errors). Investigate exceptions above; may indicate resets or parser crashes.')

    print('\n====== FINAL VERDICT ======')
    if protected:
        print('Your server shows protections for header-based abuse.')
    else:
        print('No clear protections detected for header abuse. Consider limiting header sizes and counts at the proxy level.')

    print('============================\n')


def header_injection_test():
    parser = argparse.ArgumentParser(description='Test server resilience against header-based abuses')
    parser.add_argument('url', help='Target URL')
    parser.add_argument('--concurrency', type=int, default=5, help='Parallel workers')
    parser.add_argument('--duration', type=int, default=20, help='Duration seconds')
    parser.add_argument('--max-header-kb', type=int, default=64, help='Approx max header size to attempt (KB)')
    parser.add_argument('--many-headers', type=int, default=200, help='Number of headers to send in "many headers" case')
    parser.add_argument('--duplicate-count', type=int, default=50, help='Count of duplicates to simulate (comma separated values)')

    args = parser.parse_args()
    asyncio.run(run_test(args.url, args.concurrency, args.duration, args.max_header_kb, args.many_headers, args.duplicate_count))


if __name__ == '__main__':
    header_injection_test()
